CHANGE_STATUS_TYPE_PHYSICAL_ATTACK < -  0 //力量
CHANGE_STATUS_TYPE_MAGICAL_ATTACK < -  1 //智力
CHANGE_STATUS_TYPE_MAGICAL_DEFENSE < -  2 //魔法防御
CHANGE_STATUS_TYPE_PHYSICAL_DEFENSE < -  3 //物理防御
CHANGE_STATUS_TYPE_EQUIPMENT_PHYSICAL_ATTACK < -  4 //物理伤害
CHANGE_STATUS_TYPE_EQUIPMENT_PHYSICAL_DEFENSE < -  5 //魔法伤害
CHANGE_STATUS_TYPE_PHYSICAL_ATTACK_BONUS < -  6 //物理攻击加值
CHANGE_STATUS_TYPE_MAGICAL_ATTACK_BONUS < -  7 //魔法攻击奖励
CHANGE_STATUS_TYPE_JUMP_POWER < -  8 //跳转
CHANGE_STATUS_TYPE_JUMP_SPEED_RATE < -  9 //跳跃速度
CHANGE_STATUS_TYPE_ATTACK_SPEED < -  10 //攻击速度
CHANGE_STATUS_TYPE_MOVE_SPEED < -  11 //移动速度
CHANGE_STATUS_TYPE_CAST_SPEED < -  12 //施法速度
CHANGE_STATUS_TYPE_HP_MAX < -  13 // HP MAX
CHANGE_STATUS_TYPE_HP_REGEN_RATE < -  14 // HP恢复率
CHANGE_STATUS_TYPE_PHYSICAL_CRITICAL_HIT_RATE < -  15 //物理暴击
CHANGE_STATUS_TYPE_MAGICAL_CRITICAL_HIT_RATE < -  16 //魔法暴击
CHANGE_STATUS_TYPE_PHYSICAL_BACK_ATTACK_CRITICAL < -  17 //回程致命命中概率
CHANGE_STATUS_TYPE_MAGICAL_BACK_ATTACK_CRITICAL < -  18 //回程致命命中概率
CHANGE_STATUS_TYPE_CRITICAL_TOLERANCE_RATE < -  19 //严重免疫力
CHANGE_STATUS_TYPE_ELEMENT_TOLERANCE_FIRE < -  20 //耐火性
CHANGE_STATUS_TYPE_ELEMENT_TOLERANCE_WATER < -  21 //数字属性阻力
CHANGE_STATUS_TYPE_ELEMENT_TOLERANCE_DARK < -  22 //抗癌
CHANGE_STATUS_TYPE_ELEMENT_TOLERANCE_LIGHT < -  23 //名称属性抵抗
CHANGE_STATUS_TYPE_ELEMENT_TOLERANCE_ALL < -  24 //所有属性电阻
CHANGE_STATUS_TYPE_ELEMENT_TOLERANCE_ZERO < -  25 //属性阻力0
CHANGE_STATUS_TYPE_ACTIVESTATUS_TOLERANCE_ALL < -  26 //所有州
CHANGE_STATUS_TYPE_ACTIVEPROPERTY_STUCK < -  27 //回避
CHANGE_STATUS_TYPE_BACK_ATTACK_STUCK_TOLERANCE < -  28 //背靠背卡住阻力[我适合的时候]（％）
CHANGE_STATUS_TYPE_MP_REGEN_RATE < -  29 // MP恢复速度
CHANGE_STATUS_TYPE_EXTRA_SPEED_RATE < -  30 //击中时的硬度
CHANGE_STATUS_TYPE_EQUIPMENT_MAGICAL_ATTACK < -  31 //装备魔法攻击
CHANGE_STATUS_TYPE_EQUIPMENT_MAGICAL_DEFENSE < -  32 //装备魔法防御
CHANGE_STATUS_TYPE_STUCK < -  33 //命中率
CHANGE_STATUS_TYPE_HIT_RECOVERY < -  34 //人物的硬直
CHANGE_STATUS_TYPE_MELEE_HIT_DELAY < -  35 //怪物被打后的僵直度
CAHNGE_STATUS_TYPE_EQUIPMENT_ALL_STAT < -  36 //当您提高所有设备的统计数据时。
CHANGE_STATUS_TYPE_CUSTOM < -  37
CHANGE_STATUS_TYPE_EXP_DOUBLE < -  38 //体验2x
CHANGE_STATUS_TYPE_EVIL_UP < -  39 //高马力
CHANGE_STATUS_TYPE_EVIL_DOWN < -  40 //低92马力
CHANGE_STATUS_TYPE_RIGIDITY < -  41 //刚度
CHANGE_STATUS_TYPE_ELEMENT_ATTACK_FIRE < -  42
CHANGE_STATUS_TYPE_ELEMENT_ATTACK_WATER < -  43 //增强数字属性
CHANGE_STATUS_TYPE_ELEMENT_ATTACK_DARK < -  44 //增强癌症特性
CHANGE_STATUS_TYPE_ELEMENT_ATTACK_LIGHT < -  45 //名称属性增强
CHANGE_STATUS_TYPE_ELEMENT_ATTACK_ALL < -  46 //加强所有属性
CHANGE_STATUS_TYPE_DISEASE < -  47 //疾病
CHANGE_STATUS_TYPE_MP_MAX < -  48 // MP MAX
CHANGE_STATUS_TYPE_COOLTIME_DECLINE < -  49 //技能冷却时间
CHANGE_STATUS_TYPE_PHYSICAL_CRITICAL_DAMAGE_RATE < -  50 //物理致命伤害增加率
CHANGE_STATUS_TYPE_MAGICAL_CRITICAL_DAMAGE_RATE < -  51 //魔法致命伤害增加率
CHANGE_STATUS_TYPE_BLOODWAR_GROW_ABILITY < -  52 //鲜血地牢（血塔）成长
CHANGE_STATUS_TYPE_ADDITIONAL_PHYSICAL_GENUINE_ATTACK < -  53 //独立伤害物理伤害变化
CHANGE_STATUS_TYPE_ADDITIONAL_MAGICAL_GENUINE_ATTACK < -  54 //独立伤害法术的攻击伤害变化
CHANGE_STATUS_TYPE_SUMMON_SKILL_POWER_BONUS_RATE < -  55 //增加精灵宠物的技能伤害
CHANGE_STATUS_TYPE_ANTIEVIL < -  56 //调整实际马力值
CHANGE_STATUS_TYPE_PHYSICAL_ABSOLUTE_DAMAGE < -  57 //物理绝对伤害或物理防御忽略伤害
CHANGE_STATUS_GHOST_TRAIN_NO_BREATH_TIME < -  58 //更改幻影列车窒息时间
CHANGE_STATUS_CHARACTER_LINK < -  59 //字符链接
CHANGE_STATUS_GOLD_INCREASE < -  60
CHANGE_STATUS_TYPE_MAX < -  61